econpulse:
  news:
    provider:
      type: fake
  internal:
    news-sync:
      enabled: ${ECONPULSE_INTERNAL_NEWS_SYNC_ENABLED:true}
    mapping-rebuild:
      enabled: ${ECONPULSE_INTERNAL_MAPPING_REBUILD_ENABLED:false}
    term-news-mapping:
      enabled: ${ECONPULSE_INTERNAL_TERM_NEWS_MAPPING_ENABLED:false}
